# ModernBERT Multi-Seed Experiments

This notebook fine-tunes ModernBERT for cross-domain spoiler detection on IMDb movie reviews and Goodreads book reviews.

We evaluate four settings:

1. IMDb → IMDb
2. Goodreads → Goodreads
3. IMDb → Goodreads
4. Goodreads → IMDb

To account for variation during fine-tuning, ModernBERT is trained with three random seeds: 42, 123, and 456. The final results are summarized across these runs.

The same item-based train, validation, and test splits are used for all seeds and models.

## Imports and Configuration

In [3]:
import os
import pandas as pd
import numpy as np
import torch

from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    DataCollatorWithPadding,
    TrainingArguments,
    Trainer,
    set_seed
)
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

## Load Data

In [4]:
imdb_train = pd.read_csv("data/imdb_train.csv")
imdb_val = pd.read_csv("data/imdb_val.csv")
imdb_test = pd.read_csv("data/imdb_test.csv")

goodreads_train = pd.read_csv("data/goodreads_train.csv")
goodreads_val = pd.read_csv("data/goodreads_val.csv")
goodreads_test = pd.read_csv("data/goodreads_test.csv")

datasets = {
    "IMDb train": imdb_train,
    "IMDb val": imdb_val,
    "IMDb test": imdb_test,
    "Goodreads train": goodreads_train,
    "Goodreads val": goodreads_val,
    "Goodreads test": goodreads_test,
}

for name, df in datasets.items():
    print(f"{name}: {len(df)} reviews")

IMDb train: 13913 reviews
IMDb val: 2821 reviews
IMDb test: 3266 reviews
Goodreads train: 13982 reviews
Goodreads val: 2934 reviews
Goodreads test: 3084 reviews

In [5]:
datasets = {
    "IMDb Train": imdb_train,
    "IMDb Validation": imdb_val,
    "IMDb Test": imdb_test,
    "Goodreads Train": goodreads_train,
    "Goodreads Validation": goodreads_val,
    "Goodreads Test": goodreads_test,
}

for name, df in datasets.items():
    print(name)
    print("Reviews:", len(df))
    print("Items:", df["item_id"].nunique())
    print("Spoiler %:", round(df["is_spoiler"].astype(int).mean() * 100, 2))
    print()

IMDb Train
Reviews: 13913
Items: 1079
Spoiler %: 49.81

IMDb Validation
Reviews: 2821
Items: 231
Spoiler %: 51.58

IMDb Test
Reviews: 3266
Items: 232
Spoiler %: 49.45

Goodreads Train
Reviews: 13982
Items: 7267
Spoiler %: 50.06

Goodreads Validation
Reviews: 2934
Items: 1557
Spoiler %: 49.83

Goodreads Test
Reviews: 3084
Items: 1558
Spoiler %: 49.87

In [6]:
def check_item_overlap(train, val, test, dataset_name):
    train_items = set(train["item_id"])
    val_items = set(val["item_id"])
    test_items = set(test["item_id"])

    print(f"{dataset_name}:")
    print("Train / Validation overlap:", len(train_items & val_items))
    print("Train / Test overlap:", len(train_items & test_items))
    print("Validation / Test overlap:", len(val_items & test_items))
    print()


check_item_overlap(imdb_train, imdb_val, imdb_test, "IMDb")
check_item_overlap(goodreads_train, goodreads_val, goodreads_test, "Goodreads")

IMDb:
Train / Validation overlap: 0
Train / Test overlap: 0
Validation / Test overlap: 0

Goodreads:
Train / Validation overlap: 0
Train / Test overlap: 0
Validation / Test overlap: 0

## Prepare Hugging Face Datasets

In [7]:
imdb_dataset = DatasetDict({
    "train": Dataset.from_pandas(imdb_train),
    "validation": Dataset.from_pandas(imdb_val),
    "test": Dataset.from_pandas(imdb_test)
})

goodreads_dataset = DatasetDict({
    "train": Dataset.from_pandas(goodreads_train),
    "validation": Dataset.from_pandas(goodreads_val),
    "test": Dataset.from_pandas(goodreads_test)
})

## Prepare Labels

In [8]:
def prepare_labels(example):
    example["label"] = int(example["is_spoiler"])
    return example

imdb_dataset = imdb_dataset.map(prepare_labels)
goodreads_dataset = goodreads_dataset.map(prepare_labels)

print("IMDb:", imdb_dataset["train"][0]["is_spoiler"], "->", imdb_dataset["train"][0]["label"])
print("Goodreads:", goodreads_dataset["train"][0]["is_spoiler"], "->", goodreads_dataset["train"][0]["label"])

Map:   0%|          | 0/13913 [00:00<?, ? examples/s]

Map:   0%|          | 0/2821 [00:00<?, ? examples/s]

Map:   0%|          | 0/3266 [00:00<?, ? examples/s]

Map:   0%|          | 0/13982 [00:00<?, ? examples/s]

Map:   0%|          | 0/2934 [00:00<?, ? examples/s]

Map:   0%|          | 0/3084 [00:00<?, ? examples/s]

IMDb: False -> 0
Goodreads: False -> 0

## Dataset Split Statistics

Since the datasets were split by item ID using GroupShuffleSplit, we inspect
the size, number of unique items, and class distribution of each split.
This ensures that potential differences in class distribution between
training, validation, and test sets are documented.

In [9]:
def get_split_statistics(dataset, dataset_name):
    rows = []

    for split_name in ["train", "validation", "test"]:
        split = dataset[split_name]

        labels = pd.Series(split["label"])
        spoiler_count = (labels == 1).sum()
        non_spoiler_count = (labels == 0).sum()

        rows.append({
            "Dataset": dataset_name,
            "Split": split_name,
            "Reviews": len(split),
            "Unique Items": len(set(split["item_id"])),
            "Spoilers": spoiler_count,
            "Non-Spoilers": non_spoiler_count,
            "Spoiler %": spoiler_count / len(split) * 100,
            "Non-Spoiler %": non_spoiler_count / len(split) * 100
        })

    return pd.DataFrame(rows)


split_statistics = pd.concat([
    get_split_statistics(imdb_dataset, "IMDb"),
    get_split_statistics(goodreads_dataset, "Goodreads")
], ignore_index=True)

display(split_statistics.round(2))

,Dataset,Split,Reviews,Unique Items,Spoilers,Non-Spoilers,Spoiler %,Non-Spoiler %
0,IMDb,train,13913,1079,6930,6983,49.81,50.19
1,IMDb,validation,2821,231,1455,1366,51.58,48.42
2,IMDb,test,3266,232,1615,1651,49.45,50.55
3,Goodreads,train,13982,7267,7000,6982,50.06,49.94
4,Goodreads,validation,2934,1557,1462,1472,49.83,50.17
5,Goodreads,test,3084,1558,1538,1546,49.87,50.13

## ModernBERT Tokenizer

We use `answerdotai/ModernBERT-base`. Reviews are tokenized with a maximum sequence length of 1,024 tokens to retain substantial review context while keeping fine-tuning computationally feasible.

In [10]:
checkpoint = "answerdotai/ModernBERT-base"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/1.19k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/20.8k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.13M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

In [11]:
def analyze_token_lengths(dataset, dataset_name):
    all_texts = []

    for split in ["train", "validation", "test"]:
        all_texts.extend(dataset[split]["review_text"])

    token_lengths = [
        len(tokenizer(text, truncation=False)["input_ids"])
        for text in all_texts
    ]

    print(f"{dataset_name}")
    print(f"Average length: {np.mean(token_lengths):.1f}")
    print(f"Median length: {np.median(token_lengths):.1f}")
    print(f"90th percentile: {np.percentile(token_lengths, 90):.1f}")
    print(f"95th percentile: {np.percentile(token_lengths, 95):.1f}")
    print(f"99th percentile: {np.percentile(token_lengths, 99):.1f}")
    print(f"Maximum length: {np.max(token_lengths)}")
    print(f"Over 512 tokens: {np.mean(np.array(token_lengths) > 512) * 100:.1f}%")
    print(f"Over 1024 tokens: {np.mean(np.array(token_lengths) > 1024) * 100:.1f}%")
    print()


analyze_token_lengths(imdb_dataset, "IMDb")
analyze_token_lengths(goodreads_dataset, "Goodreads")

IMDb
Average length: 362.9
Median length: 267.0
90th percentile: 751.0
95th percentile: 962.0
99th percentile: 1243.0
Maximum length: 2014
Over 512 tokens: 21.5%
Over 1024 tokens: 4.2%

Goodreads
Average length: 342.1
Median length: 239.0
90th percentile: 774.0
95th percentile: 1009.0
99th percentile: 1583.0
Maximum length: 3136
Over 512 tokens: 22.3%
Over 1024 tokens: 4.8%

## Tokenization

In [12]:
MAX_LENGTH = 1024

def tokenize_function(examples):
    return tokenizer(
        examples["review_text"],
        truncation=True,
        max_length=MAX_LENGTH
    )

tokenized_imdb = imdb_dataset.map(tokenize_function, batched=True)
tokenized_goodreads = goodreads_dataset.map(tokenize_function, batched=True)

print(tokenized_imdb["train"][0].keys())
print("IMDb token count:", len(tokenized_imdb["train"][0]["input_ids"]))
print("Goodreads token count:", len(tokenized_goodreads["train"][0]["input_ids"]))

Map:   0%|          | 0/13913 [00:00<?, ? examples/s]

Map:   0%|          | 0/2821 [00:00<?, ? examples/s]

Map:   0%|          | 0/3266 [00:00<?, ? examples/s]

Map:   0%|          | 0/13982 [00:00<?, ? examples/s]

Map:   0%|          | 0/2934 [00:00<?, ? examples/s]

Map:   0%|          | 0/3084 [00:00<?, ? examples/s]

dict_keys(['review_text', 'is_spoiler', 'item_id', 'label', 'input_ids', 'attention_mask'])
IMDb token count: 138
Goodreads token count: 71

## Dynamic Padding

In [13]:
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

## Evaluation Metrics

In [14]:
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=-1)

    return {
        "accuracy": accuracy_score(labels, predictions),
        "precision": precision_score(labels, predictions, zero_division=0),
        "recall": recall_score(labels, predictions, zero_division=0),
        "f1": f1_score(labels, predictions, zero_division=0),
        "macro_f1": f1_score(labels, predictions, average="macro", zero_division=0)
    }

## GPU Check

In [15]:
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("No GPU available.")

CUDA available: True
GPU: NVIDIA A100-SXM4-80GB

## Multi-Seed Configuration

The original data sampling and train/validation/test splits remain fixed with seed 42.
Only ModernBERT fine-tuning is repeated with three training seeds: 42, 123, and 456.

All other training hyperparameters are kept identical across seeds.
Checkpoints are stored separately for every source domain and seed.

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

MULTISEED_DIR = "/content/drive/MyDrive/NLP_Spoiler_Project/multiseed"
os.makedirs(MULTISEED_DIR, exist_ok=True)

SEEDS = [42, 123, 456]

print("Training seeds:", SEEDS)
print("Checkpoint directory:", MULTISEED_DIR)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Seeds used in the experiment: [42, 123, 456]
New seeds to train: [456]
Checkpoint directory: /content/drive/MyDrive/NLP_Spoiler_Project/multiseed

## Split Sanity Check

The dataset partitions are not regenerated for the multi-seed experiment.
We only verify again that item IDs do not overlap between train, validation, and test.

In [17]:
def check_split_overlap(train_df, val_df, test_df, name):
    train_ids = set(train_df["item_id"])
    val_ids = set(val_df["item_id"])
    test_ids = set(test_df["item_id"])

    print(name)
    print("Train/Validation overlap:", len(train_ids & val_ids))
    print("Train/Test overlap:", len(train_ids & test_ids))
    print("Validation/Test overlap:", len(val_ids & test_ids))
    print()

check_split_overlap(imdb_train, imdb_val, imdb_test, "IMDb")
check_split_overlap(goodreads_train, goodreads_val, goodreads_test, "Goodreads")

IMDb
Train/Validation overlap: 0
Train/Test overlap: 0
Validation/Test overlap: 0

Goodreads
Train/Validation overlap: 0
Train/Test overlap: 0
Validation/Test overlap: 0

## IMDb Multi-Seed Fine-Tuning

For each seed, a fresh `answerdotai/ModernBERT-base` sequence-classification model is initialized.
The model is selected exclusively by IMDb validation Macro F1 and then evaluated on both IMDb and Goodreads test data.

In [ ]:
imdb_seed_results = []

for seed in SEEDS:
    print(f"\n{'=' * 70}")
    print(f"IMDb training — seed {seed}")
    print(f"{'=' * 70}")

    set_seed(seed)

    imdb_output_dir = os.path.join(
        MULTISEED_DIR,
        f"imdb_seed_{seed}"
    )
    os.makedirs(imdb_output_dir, exist_ok=True)

    imdb_model = AutoModelForSequenceClassification.from_pretrained(
        checkpoint,
        num_labels=2
    )

    imdb_training_args = TrainingArguments(
        output_dir=imdb_output_dir,
        num_train_epochs=3,
        learning_rate=2e-5,
        per_device_train_batch_size=2,
        per_device_eval_batch_size=4,
        gradient_accumulation_steps=4,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="macro_f1",
        greater_is_better=True,
        logging_steps=100,
        save_total_limit=2,
        seed=seed,
        report_to="none"
    )

    imdb_trainer = Trainer(
        model=imdb_model,
        args=imdb_training_args,
        train_dataset=tokenized_imdb["train"],
        eval_dataset=tokenized_imdb["validation"],
        data_collator=data_collator,
        compute_metrics=compute_metrics
    )

    imdb_trainer.train()

    imdb_in_domain = imdb_trainer.evaluate(tokenized_imdb["test"])
    imdb_to_goodreads = imdb_trainer.evaluate(tokenized_goodreads["test"])

    imdb_seed_results.extend([
        {
            "Model": "ModernBERT",
            "Seed": seed,
            "Experiment": "IMDb → IMDb",
            "Accuracy": imdb_in_domain["eval_accuracy"],
            "Precision": imdb_in_domain["eval_precision"],
            "Recall": imdb_in_domain["eval_recall"],
            "F1": imdb_in_domain["eval_f1"],
            "Macro F1": imdb_in_domain["eval_macro_f1"],
        },
        {
            "Model": "ModernBERT",
            "Seed": seed,
            "Experiment": "IMDb → Goodreads",
            "Accuracy": imdb_to_goodreads["eval_accuracy"],
            "Precision": imdb_to_goodreads["eval_precision"],
            "Recall": imdb_to_goodreads["eval_recall"],
            "F1": imdb_to_goodreads["eval_f1"],
            "Macro F1": imdb_to_goodreads["eval_macro_f1"],
        }
    ])

    print(f"Finished IMDb seed {seed}")
    print("IMDb → IMDb Macro F1:", imdb_in_domain["eval_macro_f1"])
    print("IMDb → Goodreads Macro F1:", imdb_to_goodreads["eval_macro_f1"])

======================================================================
IMDb training — seed 456
======================================================================

model.safetensors: reconstructing file:   0%|          |  0.00B /  599MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.weight | MISSING    |
classifier.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Finished IMDb seed 456
IMDb → IMDb Macro F1: 0.7226276131069853
IMDb → Goodreads Macro F1: 0.7032239286401649

## Goodreads Multi-Seed Fine-Tuning

For each seed, a fresh `answerdotai/ModernBERT-base` sequence-classification model is initialized.
The model is selected exclusively by Goodreads validation Macro F1 and then evaluated on both Goodreads and IMDb test data.

In [ ]:
goodreads_seed_results = []

for seed in SEEDS:
    print(f"\n{'=' * 70}")
    print(f"Goodreads training — seed {seed}")
    print(f"{'=' * 70}")

    set_seed(seed)

    goodreads_output_dir = os.path.join(
        MULTISEED_DIR,
        f"goodreads_seed_{seed}"
    )
    os.makedirs(goodreads_output_dir, exist_ok=True)

    goodreads_model = AutoModelForSequenceClassification.from_pretrained(
        checkpoint,
        num_labels=2
    )

    goodreads_training_args = TrainingArguments(
        output_dir=goodreads_output_dir,
        num_train_epochs=3,
        learning_rate=2e-5,
        per_device_train_batch_size=2,
        per_device_eval_batch_size=4,
        gradient_accumulation_steps=4,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="macro_f1",
        greater_is_better=True,
        logging_steps=100,
        save_total_limit=2,
        seed=seed,
        report_to="none"
    )

    goodreads_trainer = Trainer(
        model=goodreads_model,
        args=goodreads_training_args,
        train_dataset=tokenized_goodreads["train"],
        eval_dataset=tokenized_goodreads["validation"],
        data_collator=data_collator,
        compute_metrics=compute_metrics
    )

    goodreads_trainer.train()

    goodreads_in_domain = goodreads_trainer.evaluate(tokenized_goodreads["test"])
    goodreads_to_imdb = goodreads_trainer.evaluate(tokenized_imdb["test"])

    goodreads_seed_results.extend([
        {
            "Model": "ModernBERT",
            "Seed": seed,
            "Experiment": "Goodreads → Goodreads",
            "Accuracy": goodreads_in_domain["eval_accuracy"],
            "Precision": goodreads_in_domain["eval_precision"],
            "Recall": goodreads_in_domain["eval_recall"],
            "F1": goodreads_in_domain["eval_f1"],
            "Macro F1": goodreads_in_domain["eval_macro_f1"],
        },
        {
            "Model": "ModernBERT",
            "Seed": seed,
            "Experiment": "Goodreads → IMDb",
            "Accuracy": goodreads_to_imdb["eval_accuracy"],
            "Precision": goodreads_to_imdb["eval_precision"],
            "Recall": goodreads_to_imdb["eval_recall"],
            "F1": goodreads_to_imdb["eval_f1"],
            "Macro F1": goodreads_to_imdb["eval_macro_f1"],
        }
    ])

    print(f"Finished Goodreads seed {seed}")
    print("Goodreads → Goodreads Macro F1:", goodreads_in_domain["eval_macro_f1"])
    print("Goodreads → IMDb Macro F1:", goodreads_to_imdb["eval_macro_f1"])

======================================================================
Goodreads training — seed 456
======================================================================

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.weight | MISSING    |
classifier.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Finished Goodreads seed 456
Goodreads → Goodreads Macro F1: 0.841718943514081
Goodreads → IMDb Macro F1: 0.6586538461538461

## Multi-Seed Results

The following cells combine all six training runs, save the per-seed results, and compute mean and sample standard deviation across the three seeds for each train–test setting.

In [ ]:
imdb_results_df = pd.DataFrame(imdb_seed_results)
goodreads_results_df = pd.DataFrame(goodreads_seed_results)

all_results = pd.concat(
    [imdb_results_df, goodreads_results_df],
    ignore_index=True
)

all_results = all_results.sort_values(
    ["Experiment", "Seed"]
).reset_index(drop=True)

display(all_results)

print("\nRows:", len(all_results))
print("Seeds:", sorted(all_results["Seed"].unique()))
print("\nResults per experiment:")
print(all_results.groupby("Experiment").size())

,Model,Seed,Experiment,Accuracy,Precision,Recall,F1,Macro F1
0,ModernBERT,42,Goodreads → Goodreads,0.852789,0.851036,0.854356,0.852693,0.852789
1,ModernBERT,123,Goodreads → Goodreads,0.841115,0.844284,0.835501,0.839869,0.841106
2,ModernBERT,456,Goodreads → Goodreads,0.841764,0.851406,0.827048,0.839050,0.841719
3,ModernBERT,42,Goodreads → IMDb,0.663503,0.691111,0.577709,0.629342,0.660620
4,ModernBERT,123,Goodreads → IMDb,0.667789,0.698949,0.576471,0.631829,0.664590
5,ModernBERT,456,Goodreads → IMDb,0.661972,0.692250,0.569659,0.625000,0.658654
6,ModernBERT,42,IMDb → Goodreads,0.731193,0.694887,0.821847,0.753053,0.729070
7,ModernBERT,123,IMDb → Goodreads,0.703632,0.658376,0.843303,0.739453,0.697922
8,ModernBERT,456,IMDb → Goodreads,0.710117,0.659722,0.864759,0.748452,0.703224
9,ModernBERT,42,IMDb → IMDb,0.731782,0.743252,0.699071,0.720485,0.731343
10,ModernBERT,123,IMDb → IMDb,0.720759,0.703532,0.752322,0.727110,0.720608
11,ModernBERT,456,IMDb → IMDb,0.724740,0.684917,0.821053,0.746832,0.722628

Rows: 12
Seeds: [np.int64(42), np.int64(123), np.int64(456)]

Results per experiment:
Experiment
Goodreads → Goodreads    3
Goodreads → IMDb         3
IMDb → Goodreads         3
IMDb → IMDb              3
dtype: int64

In [ ]:
metrics = ["Accuracy", "Precision", "Recall", "F1", "Macro F1"]

summary = (
    all_results
    .groupby("Experiment")[metrics]
    .agg(["mean", "std"])
)

display(summary)

RESULTS_DIR = "results"
os.makedirs(RESULTS_DIR, exist_ok=True)

all_results.to_csv(
    os.path.join(RESULTS_DIR, "modernbert_multiseed_results.csv"),
    index=False
)

summary.to_csv(
    os.path.join(RESULTS_DIR, "modernbert_multiseed_summary.csv")
)

print("Multi-seed results and summary saved to results/.")

                       Accuracy           Precision              Recall  \
                           mean       std      mean       std      mean
Experiment
Goodreads → Goodreads  0.845223  0.006560  0.848909  0.004009  0.838968
Goodreads → IMDb       0.664421  0.003016  0.694103  0.004235  0.574613
IMDb → Goodreads       0.714981  0.014410  0.670995  0.020702  0.843303
IMDb → IMDb            0.725760  0.005582  0.710567  0.029797  0.757482

                                       F1            Macro F1
                            std      mean       std      mean       std
Experiment
Goodreads → Goodreads  0.013980  0.843871  0.007651  0.845204  0.006575
Goodreads → IMDb       0.004334  0.628724  0.003456  0.661288  0.003024
IMDb → Goodreads       0.021456  0.746986  0.006918  0.710072  0.016665
IMDb → IMDb            0.061154  0.731475  0.013705  0.724860  0.005705

Multi-seed results and summary saved to Drive.

## Detailed Seed-42 Prediction Analysis

The detailed confidence, review-length, and qualitative error analyses used in the paper are based on the seed-42 runs.

The following cells document how the corresponding result files were derived from the cross-domain predictions of the best seed-42 checkpoints.

The exported CSV files from the original Google Colab runs are included in `results/`. Since the project was later migrated from Colab to the repository structure, these cells were not re-executed locally.

In [ ]:
from scipy.special import softmax
from sklearn.metrics import accuracy_score, recall_score, f1_score
import numpy as np
import pandas as pd
import os


def get_prediction_dataframe(trainer, tokenized_test, original_test_df):
    prediction_output = trainer.predict(tokenized_test)

    logits = prediction_output.predictions
    y_true = prediction_output.label_ids

    probabilities = softmax(logits, axis=1)
    y_pred = np.argmax(probabilities, axis=1)
    confidence = np.max(probabilities, axis=1)

    result = original_test_df.reset_index(drop=True).copy()

    result["y_true"] = y_true
    result["y_pred"] = y_pred
    result["confidence"] = confidence
    result["correct"] = result["y_true"] == result["y_pred"]

    return result

In [ ]:
imdb_to_goodreads_predictions = get_prediction_dataframe(
    imdb_trainer,
    tokenized_goodreads["test"],
    goodreads_test
)

goodreads_to_imdb_predictions = get_prediction_dataframe(
    goodreads_trainer,
    tokenized_imdb["test"],
    imdb_test
)

In [ ]:
def confidence_summary(predictions, experiment_name):
    errors = predictions[~predictions["correct"]]

    high_confidence_errors = errors[
        errors["confidence"] >= 0.90
    ]

    return {
        "Experiment": experiment_name,
        "Mean Confidence": predictions["confidence"].mean(),
        "Correct Confidence": predictions.loc[
            predictions["correct"], "confidence"
        ].mean(),
        "Incorrect Confidence": errors["confidence"].mean(),
        "Errors": len(errors),
        "High Confidence Errors": len(high_confidence_errors),
        "High Confidence Error Share":
            len(high_confidence_errors) / len(errors)
    }


confidence_results = pd.DataFrame([
    confidence_summary(
        imdb_to_goodreads_predictions,
        "IMDb → Goodreads"
    ),
    confidence_summary(
        goodreads_to_imdb_predictions,
        "Goodreads → IMDb"
    )
])

display(confidence_results)

confidence_results.to_csv(
    "results/modernbert_confidence.csv",
    index=False
)

In [ ]:
def original_token_length(text):
    return len(
        tokenizer(
            text,
            truncation=False,
            add_special_tokens=True
        )["input_ids"]
    )


def add_length_bins(predictions):
    df = predictions.copy()

    df["token_length"] = df["review_text"].apply(
        original_token_length
    )

    bins = [0, 128, 256, 512, 1024, np.inf]
    labels = [
        "≤128",
        "129–256",
        "257–512",
        "513–1024",
        ">1024"
    ]

    df["Length"] = pd.cut(
        df["token_length"],
        bins=bins,
        labels=labels,
        include_lowest=True
    )

    return df

In [ ]:
imdb_to_goodreads_predictions = add_length_bins(
    imdb_to_goodreads_predictions
)

goodreads_to_imdb_predictions = add_length_bins(
    goodreads_to_imdb_predictions
)

In [ ]:
def length_summary(predictions, experiment_name):
    rows = []

    order = [
        "≤128",
        "129–256",
        "257–512",
        "513–1024",
        ">1024"
    ]

    for length_bin in order:
        subset = predictions[
            predictions["Length"] == length_bin
        ]

        rows.append({
            "Length": length_bin,
            "N": len(subset),
            "Accuracy": accuracy_score(
                subset["y_true"],
                subset["y_pred"]
            ),
            "Recall": recall_score(
                subset["y_true"],
                subset["y_pred"],
                zero_division=0
            ),
            "Macro F1": f1_score(
                subset["y_true"],
                subset["y_pred"],
                average="macro",
                zero_division=0
            ),
            "Experiment": experiment_name
        })

    return pd.DataFrame(rows)


length_results = pd.concat([
    length_summary(
        imdb_to_goodreads_predictions,
        "IMDb → Goodreads"
    ),
    length_summary(
        goodreads_to_imdb_predictions,
        "Goodreads → IMDb"
    )
], ignore_index=True)

display(length_results)

length_results.to_csv(
    "results/modernbert_length_analysis.csv",
    index=False
)

In [ ]:
def add_error_type(predictions):
    df = predictions.copy()

    df["error_type"] = np.where(
        (df["y_true"] == 0) & (df["y_pred"] == 1),
        "FP",
        np.where(
            (df["y_true"] == 1) & (df["y_pred"] == 0),
            "FN",
            None
        )
    )

    return df

In [ ]:
imdb_to_goodreads_errors = add_error_type(
    imdb_to_goodreads_predictions
)

goodreads_to_imdb_errors = add_error_type(
    goodreads_to_imdb_predictions
)

In [ ]:
def sample_errors(predictions, direction):
    errors = predictions[
        predictions["error_type"].notna()
    ].copy()

    false_positives = errors[
        errors["error_type"] == "FP"
    ].sample(
        n=10,
        random_state=42
    )

    false_negatives = errors[
        errors["error_type"] == "FN"
    ].sample(
        n=10,
        random_state=42
    )

    sample = pd.concat(
        [false_positives, false_negatives],
        ignore_index=True
    )

    sample["direction"] = direction

    return sample

In [ ]:
error_samples = pd.concat([
    sample_errors(
        imdb_to_goodreads_errors,
        "IMDb → Goodreads"
    ),
    sample_errors(
        goodreads_to_imdb_errors,
        "Goodreads → IMDb"
    )
], ignore_index=True)

In [ ]:
error_samples = error_samples[
    [
        "review_text",
        "is_spoiler",
        "item_id",
        "y_true",
        "y_pred",
        "error_type",
        "direction"
    ]
]

display(error_samples)

error_samples.to_csv(
    "results/modernbert_cross_domain_error_sample.csv",
    index=False
)

> **Reproducibility note:**  
> The CSV files in `results/` were produced during the original Google Colab experiments and are the files used for the analyses reported in the paper. The code below documents the corresponding prediction-level analysis workflow. Because the original Colab export cells were no longer available after migrating the project to the repository structure, these reconstruction cells were added afterwards and were not re-executed locally.